### ISSUE TITLE
Invalid URLs in Railsbytes output

### ISSUE THREAD

**Issue by andyw8** [excid3/gorails-ruby#1]
Congrats on the new gem!

I noticed an issue with the URLs in the Railsbytes output:
```
A simple "hello world" example of using Rails app templates
┃ x7msKX - https://railsbytes.com/api/v1/accounts/2/templates/x7msKX
```
That URL results in a 401 (I expect it's only intended for API requests). It's valid if changed to https://railsbytes.com/templates/x7msKX

I checked the feed and it doesn't seem to currently contain a 'public' URL in the response so I expect that will need to be added on the server-side. I'm happy to open a PR to update the client once that's available.

**Comment by excid3** [comment]
Yep, good catch. 👍 

Fixed!

**Comment by andyw8** [comment]
btw it's now returning `https://railsbytes.com/public/templates/x7msKX.json` rather than `https://railsbytes.com/public/templates/x7msKX`.

**Comment by excid3** [comment]
Whoops done. 

I want to make that command interactive so you can navigate pages and select a specific template from the returned list (rather than copying the ID).
